[[redirects]]
  from = "/Men"
  to = "/Womenlistings"
  status = 301
  force = true

   [[redirects]]
  from = "/menlistings/*"
  to = "/womenlistings"
  status = 200
  force = true

  [[redirects]]
  from = "/Menlistings/*"
  to = "/Womenlistings"
  status = 200
  force = true